# This is a basic workflow to help you get started with Actions

name: yammie

# Controls when the action will run. 
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo foobar
